### ISSUE TITLE
Custom Container for Details does not get highlighted.

### ISSUE THREAD

**Issue by e0lithic** [Mister-Hope/vuepress-theme-hope#187]
Hi,

If we use the following custom container.
```
::: details
This is a details block, which does not work in IE / Edge
:::
```
Then we get the following view 
![image](https://user-images.githubusercontent.com/11680315/81779959-528b4e80-9513-11ea-9a8c-705df6dbd22c.png)

which should Ideally be something like
![image](https://user-images.githubusercontent.com/11680315/81780027-6e8ef000-9513-11ea-9321-bb91bf724196.png)

Thanks

**Comment by e0lithic** [comment]
Additional features could include

- Ability to have no title ( Would be helpful where you just want to highlight few points without specifying a title. Current keyword followed by spaces renders the keyword itself.
- Emoji support for titles. Currently emojis are not supported in the title for the custom container.

**Comment by Mister-Hope** [comment]
Got it, I will see if I can fix, this feature is brought by `vuepress-plugin-container` which is using `markdown-it-container`.

I think it's up to me for the detail issue, but the rest two, vuepress is not supporting that, you should open this issue in vuepress repo or vuepress-comunity repo. 

Since I am rebuilding vuepress with typescript by myself, I can tell you it will need a change in `@vuepress/markdown` or `@vuepress/core` for supporting emoji in titles. The emoji feature is using a edited version of `markdown-it-emoji` in package `@vuepress/markdown`, with is a built-in feature for vuepress, so I can not deal with it.

**Comment by e0lithic** [comment]
Sure I will do that

**Comment by Mister-Hope** [comment]
> Hi,
> 
> If we use the following custom container.
> 
> ```
> ::: details
> This is a details block, which does not work in IE / Edge
> :::
> ```
> 
> Then we get the following view
> ![image](https://user-images.githubusercontent.com/11680315/81779959-528b4e80-9513-11ea-9a8c-705df6dbd22c.png)
> 
> which should Ideally be something like
> ![image](https://user-images.githubusercontent.com/11680315/81780027-6e8ef000-9513-11ea-9321-bb91bf724196.png)
> 
> Thanks

 I have some trouble fixing it, in my [source code](https://github.com/Mister-Hope/vuepress-theme-hope/blob/master/packages/md-enhance/src/pluginConfig.ts#L48) I am using `Detail` , and I have no idea how it came to `DETAIL` after rendering

**Comment by e0lithic** [comment]
It seems random. This source code on your  [page](https://raw.githubusercontent.com/Mister-Hope/vuepress-theme-hope/master/docs/theme/src/en/guide/feature/theme.md) is rendering correctly while at other places it doesnt. :monocle_face:

**Comment by Mister-Hope** [comment]
Since I am not finding any problems in my source code, I am going to close it. If anyone has any idea how `Details` will be rendered to `DETAILS`, just call me, I will see if I can get a fix then.

Currently, using 

```
::: detail Details
xxxx
:::
```

as a workaround is a good idea.
