### ISSUE TITLE
[Question]How to display an image or video in fill mode inside Presentation.

### ISSUE THREAD

**Issue by piyush-das** [Mister-Hope/vuepress-theme-hope#449]
Hi,

I was using the md-enhance presentation slides and trying the following markdown where I have slightly modified the second side in the doc example to instead use a video frame. 

```md
@slidestart

## Slide 1

A paragraph with some text and a [link](https://mrhope.site)

---

<video  data-autoplay src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"></video>

---

## Slide 3.2

$$
J(\theta_0,\theta_1) = \sum_{i=0}
$$

@slideend
```

Output : 
![Screenshot from 2020-11-16 15-56-02](https://user-images.githubusercontent.com/68941107/99242274-f5a38480-2824-11eb-93cd-a8f35003ecd3.png)

However it seems that the video frame does not utilize the full slide. Are there additional configurations which can be used for achieving the same?

Thanks

**Comment by Mister-Hope** [comment]
It's possible for you to use:

```html
<video controls style="width: 100%" data-autoplay src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" />
```

**Comment by Mister-Hope** [comment]
I am not familiar with reveal.js. I am just adding support because some of my users want this feature.

For usage, I suggest you to look in to [reveal.js](https://revealjs.com/) for help.

If you do found something is behaving differnt between my theme and a webpage embed with reveal,js, feel free to open an issue with “Bugs" label,

**Comment by piyush-das** [comment]
Ok Thanks.
